version: "3"
services:
  scroll-id-domain-queue:
    image: scroll-id-domain-worker
    build:
      context: .
      dockerfile: Dockerfile-server
    restart: always
    volumes:
      - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q dns-domain-queue -l INFO -c 4

networks:
  base-network:
    external: true
